version: '3.9'
services:
  api:
    container_name: shibartender-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    env_file: env_docker.env
    networks:
      - shibartender-net
  mongo:
    container_name: shibartender-mongo
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    ports:
      - "27018:27017"
    networks:
      - shibartender-net

volumes:
  mongo-data:
    name: shibartender-mongo

networks:
  shibartender-net:
    name: shibartender-network